# permissions for end users to edit demoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-editor-role
rules:
- apiGroups:
  - apaas.envisioncn.com.apaas.envisioncn.com
  resources:
  - demoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apaas.envisioncn.com.apaas.envisioncn.com
  resources:
  - demoes/status
  verbs:
  - get
