## Append samples you want in your CSV to this file as resources ##
resources:
- apaas.envisioncn.com_v1beta1_demo.yaml
- apaas.envisioncn.com_v1_demo.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
